### ISSUE TITLE
Title spacing and font size

### ISSUE THREAD

**Issue by CesarFelipe** [BrOrlandi/StarWarsIntroCreator#13]
In order to more closely match the originals, the title lines need two adjustments. First, the font size of the second title ("A NEW HOPE") should be larger than the main text. I tried looking for specific value but couldn't find any reference. (The size of the first title "Episode IV" seems to be smaller than the main text but that may be an illusion, so it's not an issue per se.)

Second, more spacing between the titles and the main text needs to be added. The space between the first title and the second title should increase by a small amount, while the space between the second title and the main text needs a more significant increase. As it is right now it has the same spacing as the main text lines have with each other, which makes the titles look quite off.

**Comment by mheguy** [comment]
Noticed the same. Would also mention the main body text should occupy more of the frame. For reference: [http://i.imgur.com/V8fBJpZ.png](http://i.imgur.com/V8fBJpZ.png)

**Comment by BrOrlandi** [comment]
@plague006 created the issue #19 about your comment. Thank you!
