### ISSUE TITLE
No guide / wiki / tutorials and not enough documentation

### ISSUE THREAD

**Issue by aaronfranke** [BrOrlandi/StarWarsIntroCreator#17]
At the moment this tool isn't very obvious on how to use it. The GitHub repo should contain a tutorial and more documentation.

**Comment by BrOrlandi** [comment]
@aaronfranke could  you tell us the difficults you have found? A tutorial on the website would help?

**Comment by aaronfranke** [comment]
Like, I don't know how to get started. I don't know how to use this at all because there are no instructions. I am stuck after cloning the repo. There needs to be instructions.

**Comment by BrOrlandi** [comment]
What you want to develop with it?
Did you checked the website? brorlandi.github.io/StarWarsIntroCreator/
The application is simple, has a "package.json" and a "gulpfile.js", just need to run gulp to start developing.

**Comment by aaronfranke** [comment]
I see now that the top image links to that page, but the link to there should be more obvious.

There is no document to tell me that I need to use gulp, or how to use it. Someone wouldn't know what to do if they didn't know what a gulpfile.js was.

**Comment by BrOrlandi** [comment]
So as I understand you just wanna run the website, not develop it. I put the link in the README.md too. As it has a package.json file it is a NPM project, so anyone who wants to develop with this project needs to know the basic of NPM. I think it doesn't need a very detailed documentation.
