### ISSUE TITLE
Is this HTML and CSS page (not video) open source?

### ISSUE THREAD

**Issue by gusbemacbe** [BrOrlandi/StarWarsIntroCreator#22]
Hi,

I would like to use it for my school project, because my story is about Star Wars. 

I tried two Star Wars templates in HTML and CSS, but in the first template, the logotype shakes and in the second template, the starting of "A long time ago" doesn't fulfil the black background.

I found only your template so smooth and relevant.

**Comment by BrOrlandi** [comment]
Yes, it's open source right in this repository! 👍
