### ISSUE TITLE
Loop audio to allow for longer text crawl

### ISSUE THREAD

**Issue by ama4tf** [BrOrlandi/StarWarsIntroCreator#4]
You can barely do a paragraph before it cuts off

**Comment by BrOrlandi** [comment]
Was developed to have the same time as the movie have, and has the death star at the end. You need to write your intro in the same length as the movies intros.

**Comment by Simon-Tang** [comment]
Perhaps we should have an indicator for roughly how many lines are remaining until the speed of the text has to be increased?

**Comment by BrOrlandi** [comment]
@ama4tf @Simon-Tang I've tested on Firefox and Chrome, it works well for me. Can you test if it's improved for longer texts now?
Thanks
