### ISSUE TITLE
Let users edit Star Wars logo 

### ISSUE THREAD

**Issue by airon90** [BrOrlandi/StarWarsIntroCreator#5]
I'd like not to use "Star Wars" text but to write something else with the same font.
Is it possible to change the software to add this feature? :)

**Comment by Potherca** [comment]
Looking at the source code, [the "Star Wars" text is an SVG image](https://github.com/BrOrlandi/StarWarsIntroCreator/blob/master/public/logo.svg). 

There is, however, [a very similar looking font](http://www.fontsquirrel.com/fonts/Distant-Galaxy) that _could_ be used for this purpose.

Theoretically, it shouldn't take more than adding an entry field, adding JS logic to place the text in the right place and scale the input to fit its container.

In practise, I assume, fiddling around with various texts/length would be required to get everything looking proper.

And of course someone would need to find/make the time to actually implement this :grinning:

**Comment by BrOrlandi** [comment]
@potherca I've used the [Starjedi font](http://www.dafont.com/pt/star-jedi.font) in the title of the page.
Both of these fonts are filled, to have the same effect as the logo it should be outlined with a yellow border and a transparent fill.
I'll check if this is possible. :wink:

**Comment by BrOrlandi** [comment]
@Airon90 @potherca Done!

**Comment by Potherca** [comment]
:+1: Awesome!
