### ISSUE TITLE
Add video recording option

### ISSUE THREAD

**Issue by nihey** [BrOrlandi/StarWarsIntroCreator#8]
It was originally proposed on ProductHunt, I'll be working on it.

**Comment by nihey** [comment]
We'll it has been a while, and I was rather busy. But I managed to make a recorder for this project. If you want to see a example of video generated with it, [look here](https://youtu.be/mbSQcovyX7A), a rather popular intro generated by the community (the video is still not perfect, but it'll get better).

I can produce a `720p` video locally, but If we want to make this completely automated we will need a server infrastructure that we do not have right now. I'll try to come up with a local `DDNSed` server on my house, but it is not very powerful, and does not have the most perfect availability, but it should do the work for now. This should be done by the end of the next weekend.

We encourage anyone out there have a good server infrastructure (AWS, DigitalOcean, ...) and would be willing to share it to deploy this (but It has to have `1.5GB+` free RAM) to step up. **Donations are also encouraged**, if we get enough money to support a good enough `VPS` for some time, we will surely do it.

As for now (untill the end of the weekend), anyone who has an urge to a video intro can contact me (@nihey) or @BrOrlandi and I'll locally generate it for you.

**Comment by nihey** [comment]
Well, I think it can be considered as `fixed`.

StarWarsIntroRecorder is handling the video recording on a DDNSed server. If we get a regular source of income from donations, the video quality can be improved (by using a SSD server) and maybe the rendering time can be reduced as well.

Have a great time on the recording queue, gentleman!

**Comment by joeskeen** [comment]
@nihey it appears that your link to the StarWarsIntroRecorder repository is dead.  Did it move someplace else?

**Comment by nihey** [comment]
@joeskeen Unfortunately we had to move it to gitlab and close the source of it, as it started to be used on some other non Open Source projects.

But in any case, the solution it implemented is a bit legacy by now.
